import sqlite3, config

connection = sqlite3.connect(config.DB_FILE)

cursor = connection.cursor()

cursor.execute("""

CREATE TABLE IF NOT EXISTS income_annual_general (

        id INTEGER PRIMARY KEY, 
        stock_id INTEGER NOT NULL,
        fiscal_year INTEGER, 
        fiscal_period, 
        report_date TEXT, 
        publish_date TEXT, 
        restated_date TEXT, 
        shares_basic, 
        shares_diluted, 
        source, 
        revenue, 
        sales_services_revenue, 
        financing_revenue, 
        other_revenue, 
        cost_revenue, 
        cost_goods_services, 
        cost_financing_revenue, 
        cost_other_revenue, 
        gross_profit, 
        other_op_income, 
        operating_expenses, 
        selling_gen_admin, 
        selling_marketing, 
        gen_admin, 
        research_dev, 
        depr_amor, 
        prov_doubt_acc, 
        other_op_expense, 
        op_income, 
        non_op_income, 
        interest_exp_net, 
        interest_exp, 
        interest_income, 
        other_invest_income, 
        fx_gain_loss, 
        income_affil, 
        other_non_op_income, 
        pretax_income_loss_adj, 
        abnorm_gain_loss, 
        acq_in_process_rd, 
        merger_acq_expense, 
        abnorm_deriv, 
        disposal_assets, 
        early_ext_debt, 
        asset_writedown, 
        impair_goodwill_int, 
        sale_business, 
        legal_settlement, 
        restr_charges, 
        sale_investments, 
        insurance_settlement, 
        other_abnorm, 
        pretax_income_loss, 
        income_tax, 
        tax_current, 
        tax_deferred, 
        tax_allowance, 
        income_affil_net_tax, 
        income_cont_op, 
        net_extr_gain_loss, 
        discontinued_operations, 
        acc_charges, 
        income_incl_minority, 
        minority_interest , 
        net_income, 
        preferred_dividends INTEGER, 
        other_adj INTEGER, 
        net_income_common INTEGER, 

        FOREIGN KEY (stock_id) REFERENCES stock (id)

    )
""")

# Balance Sheet
cursor.execute("""

CREATE TABLE IF NOT EXISTS balance_annual_general (
    id INTEGER PRIMARY KEY,
    stock_id INTEGER NOT NULL,
    fiscal_year INTEGER, 
    fiscal_period, 
    report_date TEXT, 
    publish_date TEXT, 
    restated_date TEXT, 
    shares_basic, 
    shares_diluted,
    cash_equiv_st_invest,
    cash_equiv, 
    st_invest, 
    acc_notes_recv, 
    acc_recv_net, 
    notes_recv_net, 
    unbilled_revenue, 
    inventories, 
    raw_materials, 
    work_in_process, 
    finished_goods, 
    other_inventory, 
    other_st_assets, 
    prepaid_expenses, 
    deriv_hedg_assets_st, 
    assets_hfs, 
    def_tax_assets_st, 
    income_tax_recv, 
    discontinued_operations_st, 
    misc_st_assets, 
    total_cur_assets, 
    ppe_net, 
    ppe, 
    accum_depr, 
    lt_invest_recv, 
    lt_invest, 
    lt_market_sec, 
    lt_recv, 
    other_lt_assets, 
    intangibles, 
    goodwill, 
    other_intangibles, 
    prepaid_expense, 
    def_tax_assets_lt, 
    deriv_hedg_assets_lt, 
    prepaid_pension_costs, 
    discontinued_operations_lt, 
    invest_affil, 
    misc_lt_assets, 
    total_noncur_assets, 
    total_assets, 
    payables_accruals, 
    accounts_payable, 
    accrued_taxes, 
    int_div_payable, 
    other_payables, 
    st_debt, 
    st_borrowings, 
    st_capital_leases, 
    cur_port_lt_debt, 
    other_st_liab, 
    def_revenue_st, 
    liab_deriv_hedg_st, 
    def_tax_liab_st, 
    liab_discop_st, 
    misc_st_liab, 
    total_cur_liab, 
    lt_debt, 
    lt_borrowings, 
    lt_capital_leases, 
    other_lt_liab, 
    accrued_liab, 
    pension_liab, 
    pensions, 
    other_post_ret_ben, 
    def_comp, 
    def_revenue_lt, 
    def_tax_liab_lt, 
    liab_deriv_hedg_lt, 
    liab_discop_lt, 
    misc_lt_liab, 
    total_noncur_liab, 
    total_liab, 
    preferred_equity, 
    share_capital_add, 
    common_stock, 
    add_paid_in_capital, 
    other_share_capital, 
    treasury_stock, 
    retained_earnings, 
    other_equity, 
    equity_before_minority, 
    minority_interest, 
    total_equity, 
    total_liab_equity,

        FOREIGN KEY (stock_id) REFERENCES stock (id)

    )
""")

cursor.execute("""

CREATE TABLE IF NOT EXISTS cashflow_annual_general (

        id INTEGER PRIMARY KEY, 
        stock_id INTEGER NOT NULL,
        fiscal_year INTEGER, 
        fiscal_period, 
        report_date TEXT, 
        publish_date TEXT, 
        restated_date TEXT, 
        shares_basic, 
        shares_diluted,
        net_income, 
        net_income_discop, 
        other_adj, 
        net_income_start, 
        depr_amor, 
        non_cash_items, 
        stock_comp, 
        def_income_taxes, 
        other_non_cash_adj, 
        chg_working_capital, 
        chg_accounts_recv, 
        chg_inventories, 
        chg_acc_payable, 
        chg_other, 
        net_cash_discop_oper, 
        net_cash_ops, 
        capex, 
        disp_fix_assets_int, 
        disp_fix_assets, 
        disp_int_assets, 
        acq_fix_assets_int, 
        purch_fix_assets, 
        acq_int_assets, 
        other_chg_fix_assets_int, 
        net_chg_lt_invest, 
        decr_lt_invest, 
        incr_lt_invest, 
        net_cash_acq_divest, 
        net_cash_divest, 
        cash_acq_sub, 
        cash_joint_ventures, 
        net_cash_other_acq, 
        other_invest_act, 
        net_cash_discop_invest, 
        net_cash_inv, 
        dividends_paid, 
        cash_repay_debt, 
        cash_repay_st_debt, 
        cash_repay_lt_debt, 
        repay_lt_debt, 
        cash_lt_debt, 
        cash_repurchase_equity, 
        incr_capital_stock, 
        decr_capital_stock, 
        other_fin_act, 
        net_cash_discop_fin, 
        net_cash_fin, 
        net_cash_before_discop_fx, 
        chg_cash_discop_other, 
        net_cash_before_fx, 
        effect_fx_rates, 
        net_chg_cash,

        FOREIGN KEY (stock_id) REFERENCES stock (id)

    )
""")





#QUARTERLY TABLES

cursor.execute("""

CREATE TABLE IF NOT EXISTS income_quarter_general (

        id INTEGER PRIMARY KEY, 
        stock_id INTEGER NOT NULL,
        fiscal_year INTEGER, 
        fiscal_period TEXT, 
        report_date TEXT, 
        publish_date TEXT, 
        restated_date TEXT, 
        shares_basic, 
        shares_diluted, 
        source, 
        revenue, 
        sales_services_revenue, 
        financing_revenue, 
        other_revenue, 
        cost_revenue, 
        cost_goods_services, 
        cost_financing_revenue, 
        cost_other_revenue, 
        gross_profit, 
        other_op_income, 
        operating_expenses, 
        selling_gen_admin, 
        selling_marketing, 
        gen_admin, 
        research_dev, 
        depr_amor, 
        prov_doubt_acc, 
        other_op_expense, 
        op_income, 
        non_op_income, 
        interest_exp_net, 
        interest_exp, 
        interest_income, 
        other_invest_income, 
        fx_gain_loss, 
        income_affil, 
        other_non_op_income, 
        pretax_income_loss_adj, 
        abnorm_gain_loss, 
        acq_in_process_rd, 
        merger_acq_expense, 
        abnorm_deriv, 
        disposal_assets, 
        early_ext_debt, 
        asset_writedown, 
        impair_goodwill_int, 
        sale_business, 
        legal_settlement, 
        restr_charges, 
        sale_investments, 
        insurance_settlement, 
        other_abnorm, 
        pretax_income_loss, 
        income_tax, 
        tax_current, 
        tax_deferred, 
        tax_allowance, 
        income_affil_net_tax, 
        income_cont_op, 
        net_extr_gain_loss, 
        discontinued_operations, 
        acc_charges, 
        income_incl_minority, 
        minority_interest , 
        net_income, 
        preferred_dividends INTEGER, 
        other_adj INTEGER, 
        net_income_common INTEGER, 

        FOREIGN KEY (stock_id) REFERENCES stock (id)

    )
""")

# Balance Sheet
cursor.execute("""

CREATE TABLE IF NOT EXISTS balance_quarter_general (
    id INTEGER PRIMARY KEY,
    stock_id INTEGER NOT NULL,
    fiscal_year INTEGER, 
    fiscal_period TEXT, 
    report_date TEXT, 
    publish_date TEXT, 
    restated_date TEXT, 
    shares_basic, 
    shares_diluted,
    cash_equiv_st_invest,
    cash_equiv, 
    st_invest, 
    acc_notes_recv, 
    acc_recv_net, 
    notes_recv_net, 
    unbilled_revenue, 
    inventories, 
    raw_materials, 
    work_in_process, 
    finished_goods, 
    other_inventory, 
    other_st_assets, 
    prepaid_expenses, 
    deriv_hedg_assets_st, 
    assets_hfs, 
    def_tax_assets_st, 
    income_tax_recv, 
    discontinued_operations_st, 
    misc_st_assets, 
    total_cur_assets, 
    ppe_net, 
    ppe, 
    accum_depr, 
    lt_invest_recv, 
    lt_invest, 
    lt_market_sec, 
    lt_recv, 
    other_lt_assets, 
    intangibles, 
    goodwill, 
    other_intangibles, 
    prepaid_expense, 
    def_tax_assets_lt, 
    deriv_hedg_assets_lt, 
    prepaid_pension_costs, 
    discontinued_operations_lt, 
    invest_affil, 
    misc_lt_assets, 
    total_noncur_assets, 
    total_assets, 
    payables_accruals, 
    accounts_payable, 
    accrued_taxes, 
    int_div_payable, 
    other_payables, 
    st_debt, 
    st_borrowings, 
    st_capital_leases, 
    cur_port_lt_debt, 
    other_st_liab, 
    def_revenue_st, 
    liab_deriv_hedg_st, 
    def_tax_liab_st, 
    liab_discop_st, 
    misc_st_liab, 
    total_cur_liab, 
    lt_debt, 
    lt_borrowings, 
    lt_capital_leases, 
    other_lt_liab, 
    accrued_liab, 
    pension_liab, 
    pensions, 
    other_post_ret_ben, 
    def_comp, 
    def_revenue_lt, 
    def_tax_liab_lt, 
    liab_deriv_hedg_lt, 
    liab_discop_lt, 
    misc_lt_liab, 
    total_noncur_liab, 
    total_liab, 
    preferred_equity, 
    share_capital_add, 
    common_stock, 
    add_paid_in_capital, 
    other_share_capital, 
    treasury_stock, 
    retained_earnings, 
    other_equity, 
    equity_before_minority, 
    minority_interest, 
    total_equity, 
    total_liab_equity,

        FOREIGN KEY (stock_id) REFERENCES stock (id)

    )
""")

cursor.execute("""

CREATE TABLE IF NOT EXISTS cashflow_quarter_general (

        id INTEGER PRIMARY KEY, 
        stock_id INTEGER NOT NULL,
        fiscal_year INTEGER, 
        fiscal_period TEXT, 
        report_date TEXT, 
        publish_date TEXT, 
        restated_date TEXT, 
        shares_basic, 
        shares_diluted,
        net_income, 
        net_income_discop, 
        other_adj, 
        net_income_start, 
        depr_amor, 
        non_cash_items, 
        stock_comp, 
        def_income_taxes, 
        other_non_cash_adj, 
        chg_working_capital, 
        chg_accounts_recv, 
        chg_inventories, 
        chg_acc_payable, 
        chg_other, 
        net_cash_discop_oper, 
        net_cash_ops, 
        capex, 
        disp_fix_assets_int, 
        disp_fix_assets, 
        disp_int_assets, 
        acq_fix_assets_int, 
        purch_fix_assets, 
        acq_int_assets, 
        other_chg_fix_assets_int, 
        net_chg_lt_invest, 
        decr_lt_invest, 
        incr_lt_invest, 
        net_cash_acq_divest, 
        net_cash_divest, 
        cash_acq_sub, 
        cash_joint_ventures, 
        net_cash_other_acq, 
        other_invest_act, 
        net_cash_discop_invest, 
        net_cash_inv, 
        dividends_paid, 
        cash_repay_debt, 
        cash_repay_st_debt, 
        cash_repay_lt_debt, 
        repay_lt_debt, 
        cash_lt_debt, 
        cash_repurchase_equity, 
        incr_capital_stock, 
        decr_capital_stock, 
        other_fin_act, 
        net_cash_discop_fin, 
        net_cash_fin, 
        net_cash_before_discop_fx, 
        chg_cash_discop_other, 
        net_cash_before_fx, 
        effect_fx_rates, 
        net_chg_cash,

        FOREIGN KEY (stock_id) REFERENCES stock (id)

    )
""")

cursor.execute("""
    CREATE TABLE IF NOT EXISTS simfin_stock_price (
        id INTEGER PRIMARY KEY, 
        stock_id INTEGER,
        simfin_id INTEGER NOT NULL,
        sector TEXT,
        industry TEXT,
        date NOT NULL,
        open NOT NULL, 
        low NOT NULL,
        high NOT NULL, 
        close NOT NULL,
        adj_close,
        dividends,
        volume,
        shares_outstanding,
        FOREIGN KEY (stock_id) REFERENCES stock (id)
    )
""")




connection.commit()